/**
 * @deprecated soon, please make sure to update any class changes on src/packages/vcs-classes/src/models/errorEnums.js
 */
const VCS_ERROR_PHASES = {
    SETUP_SCAN: 'SETUP_SCAN',
    SYNC_REPOSITORIES: 'SYNC_REPOSITORIES',
    GET_REPOSITORIES_FILES_STRUCTURE: 'GET_REPOSITORIES_FILES_STRUCTURE',
    DOWNLOAD_FILES: 'DOWNLOAD_FILES'
};

const ERROR_HIGH_CLASSIFICATION_RATIO = {
    [VCS_ERROR_PHASES.SYNC_REPOSITORIES]: 0.1,
    [VCS_ERROR_PHASES.GET_REPOSITORIES_FILES_STRUCTURE]: 0.1,
    [VCS_ERROR_PHASES.DOWNLOAD_FILES]: 0.1
};

const ERROR_CLASSIFICATION = {
    HIGH: 'HIGH',
    LOW: 'LOW'
};

module.exports = { VCS_ERROR_PHASES, ERROR_CLASSIFICATION, ERROR_HIGH_CLASSIFICATION_RATIO };